apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-shared-pv
  namespace: mediaserver
spec:
  accessModes:
    - ReadWriteMany # NFS supports ReadWriteMany (multiple pods reading/writing)
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 155Gi
  volumeName: pvc-bd169f1f-451e-4f7e-8221-774140d181bf
