apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-transmission-pvc
  namespace: mediaserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
