- name: Install server packages
  become: true
  hosts: servers
  tasks:
    - name: Mount up external ssd
      ansible.posix.mount:
        path: /mnt/ssd01/
        src: UUID=67FE-BEA0
        fstype: exfat
        opts: rw,uid=2001,gid=2000,umask=0002
        state: mounted
