storage_pools:
  - name: vg_ssd
    disks: [sda]
    volumes:
      - name: containers
        size: "20 GiB"
        mount_point: /var/lib/containers
        state: present
        fs_type: xfs
      - name: media
        size: "180 GiB"
        mount_point: /mnt/media
        state: present
        fs_type: xfs

# node_specific_packages:
#   - podman
#   - elrepo-release
#   - podman-compose
