apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong-gc-01
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller-01

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong-gw-01
  namespace: kong
  annotations:
    konghq.com/publish-service: kong/kong-gw-01-kong-proxy  # Tells KIC which service to use for the LoadBalancer IP/hostname
spec:
  gatewayClassName: kong-gc-01
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: proxy-https-wildcard
    port: 443
    protocol: HTTPS
    hostname: "*.k.4esnok.su"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-4esnok-su-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: proxy-https-base
    port: 443
    protocol: HTTPS
    hostname: "k.4esnok.su"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-4esnok-su-tls
    allowedRoutes:
      namespaces:
        from: All
