# values-enterprise-kic.yaml for Kong Enterprise API Gateway
# Uses DB-less mode, operating as a Kubernetes Ingress Controller (KIC + DP) with Enterprise features enabled

image:
  repository: kong/kong-gateway
  tag: "3.10-rhel"

enterprise:
  enabled: true
  # Refers to the secret containing the Kong Enterprise license
  license_secret: kong-enterprise-license
  vitals:
    enabled: true

env:
  database: "off"
  role: "traditional" # In DBC-less or traditional mode, not hybrid
  admin_listen: "0.0.0.0:8001, 0.0.0.0:8444 http2 ssl"
  admin_gui_url: "https://k.4esnok.su/manager"
  admin_gui_api_url: "https://k.4esnok.su/admin"
  admin_gui_path: "/manager"

# Kong Ingress Controller configuration
ingressController:
  enabled: true
  installCRDs: false # Keeps the existing behavior of not letting Helm manage CRDs
  env:
    # Explicitly matches the controllerName used in GatewayClass
    gateway_api_controller_name: konghq.com/kic-gateway-controller-01

# Kong proxy service configuration
proxy:
  enabled: true
  type: LoadBalancer 
  http:
    enabled: true
  tls:
    enabled: true

# Kong Admin API service configuration
admin:
  enabled: true
  type: ClusterIP 
  http:
    enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false
