services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ${media_dir}/config:/config:z
      - ${media_dir}:/downloads:z
      - ${media_dir}/watch:/watch:z
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - app-net

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - jackett-vol:/config
      - ${media_dir}/watch:/downloads:z
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - app-net
  
  samba:
    image: docker.io/dperson/samba:latest
    container_name: samba
    # command: -u "blomerus;${ADMIN_PASSWORD}" -s "media;/share;yes;no;no;blomerus" -s "public;/public;yes;no;yes"
    command: -s "public;/public;yes;no;yes"
    volumes:
      # - ${DATA_DIR}:/share
      # - ${DATA_DIR}/public:/public
      - ${media_dir}/watch:/share:z
      - ${media_dir}:/public:z
    environment:
      - TZ=Etc/UTC
      - WORKGROUP=malinka.lan
      - USERID=1000
      - GROUPID=1000
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    networks:
      - app-net


networks:
  app-net: {}

volumes:
  jackett-vol: {}
