services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - type: volume
        source: transmission-vol
        target: /config

      # "selinux: z" is not implemented in podman-compose 1.0.6
      # - type: bind
      #   source: ${working_dir}/transmission_conf/settings.json
      #   target: /config/settings.json
      #   bind:
      #     selinux: z
      - ${working_dir}/transmission_conf/settings.json:/config/settings.json:z

      # - type: bind
      #   source: ${media_dir}
      #   target: /media
      #   bind:
      #     selinux: z
      #     create_host_path: true
      - ${media_dir}:/media:z

      # - type: bind
      #   source: ${media_dir}/watch
      #   target: /watch
      #   bind:
      #     selinux: z
      #     create_host_path: true
      - ${media_dir}/watch:/watch:z

    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - app-net

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - AUTO_UPDATE=true #optional
  #     - RUN_OPTS= #optional
  #   volumes:
  #     - jackett-vol:/config
  #     - ${media_dir}/watch:/downloads:z
  #   ports:
  #     - 9117:9117
  #   restart: unless-stopped
  #   networks:
  #     - app-net
  
  samba:
    image: docker.io/dperson/samba:latest
    container_name: samba
    # command: -u "blomerus;${ADMIN_PASSWORD}" -s "media;/share;yes;no;no;blomerus" -s "public;/public;yes;no;yes"
    # command: -u "alex;${ADMIN_PASSWORD}" #-s "torrents;/torrents;yes;yes;yes" -s "watch;/watch;yes;no;no;alex"
    volumes:
      # - ${DATA_DIR}:/share
      # - ${DATA_DIR}/public:/public
      # - ${media_dir}/watch:/watch:z
      - ${media_dir}:/transmission:z
    environment:
      - TZ=Etc/UTC
      - WORKGROUP=malinka.lan
      - USERID=1000
      - GROUPID=1000
      - SHARE1=transmission;/transmission;yes;yes;yes
      - SHARE2=admin;/transmission;yes;no;no;alex
      - USER1=alex;${ADMIN_PASSWORD}
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net: {}

volumes:
  transmission-vol:
    name: transmission-config
  jackett-vol:
    name: jackett-config
