services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - /home/alexander/temp/transmission/config:/config:Z
      - /home/alexander/temp/transmission:/downloads:Z
      - /home/alexander/temp/transmission/watch:/watch:Z
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - app-net

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - AUTO_UPDATE=true #optional
  #     - RUN_OPTS= #optional
  #   volumes:
  #     - jackett-vol:/config
  #     - /home/alexander/temp/transmission/watch:/downloads:Z
  #   ports:
  #     - 9117:9117
  #   restart: unless-stopped


networks:
  app-net: {}

volumes:
  jackett-vol: {}
