groups:
  - name: container.rules
    interval: 30s
    rules:
      - record: container:cpu_usage:rate
        expr: |
          sum by (instance) (
            rate(container_cpu_usage_seconds_total[5m])
          )
      - record: container:memory_usage:ratio
        expr: |
          sum by (container, instance) (
            container_memory_working_set_bytes
            )
