apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app-deployment
  name: nginx-app
  namespace: nginx-smoke-test
spec:
  replicas: 16
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - image: nginx
          name: nginx-container
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
          - containerPort: 80
