apiVersion: v1
kind: Service
metadata:
  name: nginx-smoke-test
  labels:
    app: nginx
  namespace: nginx-smoke-test
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080