services:
  devcontainer:
    container_name: devcontainer
    hostname: devcontainer
    volumes:
      - ..:/workspace:cached
    build:
      context: ..
      dockerfile: .devcontainer/Containerfile
    tty: true
#   # OnePassword Connect service containers
#   op-connect-api:
#     container_name: op-api
#     image: 1password/connect-api:latest
#     # ports:
#     #   - "8080:8080"
#     volumes:
#       - "../.onepass/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
#       - "op-data:/home/opuser/.op/data"
#   op-connect-sync:
#     container_name: op-sync
#     image: 1password/connect-sync:latest
#     # ports:
#     #   - "8081:8080"
#     volumes:
#       - "../.onepass/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
#       - "op-data:/home/opuser/.op/data"
# volumes:
#   op-data:


###### PLAYBOOK EXAMPLE ######
    # - name: Get secret from 1password
    #   onepassword.connect.item_info:
    #     vault: malinka
    #     # token: "{{ op_token }}"
    #     item: malinka3_root
    #     # field: password
    #     # hostname: http://op-api:8080
    #     # hostname: https://my.1password.com
    #   register: op_item_info
    #   delegate_to: localhost
    #   run_once: true
    #   environment:
    #     OP_TOKEN: "{{ op_token }}"
    #   # no_log: true