---
- name: Check apache2 status
  hosts: malinka
  tasks:
    - name: Check httpd status
      ansible.builtin.command:
        cmd: systemctl status apache2
      register: result
      changed_when: result.rc != 0

    - name: Dispaly httpd status
      ansible.builtin.debug:
        var: result
