- name: Display ansible_facts
  hosts: all
  tasks:
    - name: Display the fact
      ansible.builtin.debug:
        var: ansible_facts.distribution
    # - name: Display facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
