---
- name: Install Apache and starts the service
  hosts: malinka
  tasks:
    - name: Install the required package
      ansible.builtin.apt:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
        state: present

    - name: Start the service
      ansible.builtin.service:
        name: "{{ ansible_facts.ansible_local.custom.general.service }}"
        state: "{{ ansible_facts.ansible_local.custom.general.state }}"
        enabled: "{{ ansible_facts.ansible_local.custom.general.enabled }}"
