---
- name: Initial Ansible node setup
  hosts: '{{ host | default("raspberries") }}'
  become: false
  gather_facts: false
  vars_files:
    - ../vars/secrets.yml
  remote_user: root
  tasks:
    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        comment: Ansible user
        shell: /bin/bash
        password: "{{ ansible_user_pass | password_hash('sha512') }}"
        state: present
      when: ansible_user != 'ansible'
      changed_when: false

    - name: Allow ansible user to sudo without password
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'
      when: ansible_user != 'ansible'

    - name: Set authorized key for ansible user
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: ansible_user != 'ansible'

    - name: Reset root password
      ansible.builtin.user:
        name: root
        password: "{{ root_pass | password_hash('sha512') }}"
        update_password: always
      changed_when: false
