---
- name: Media server setup
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  vars:
    user: '1000'
    group: '1000'
    # podman_compose_path: /usr/local/bin/podman-compose
    podman_compose_path: /bin/podman-compose
    media_dir: /mnt/media


  tasks:
    - name: Create torrents directory
      ansible.builtin.file:
        path: /mnt/media/torrents
        state: directory
        mode: '2775'
        owner: 1000
        group: 1000

    - name: Install additional packages
      ansible.builtin.dnf:
        state: present
        name:
          - podman
          - python3-pip

    # - name: Install podman-compose from pip  # Alma9 repos don't have podman-compose
    #   ansible.builtin.pip:
    #     name: podman-compose

    # system_u:object_r:container_var_lib_t:s0
    # - name: Set SELinux labels on the container's dir
    #   ansible.builtin.file:
    #     path: /var/lib/containers
    #     state: directory
    #     setype: container_var_lib_t

    # systemd can't read the environment file if it has incorrect context
    - name: Set SELinux context for the environment file
      ansible.builtin.file:
        path: "{{ media_dir }}/service/.env"
        state: file
        setype: etc_t

    - name: Configure firewall
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        state: "enabled"
        port: "{{ item }}"
      loop:
        - "9091/tcp"
        - "51413/udp"
        - "51413/tcp"
        - "139/tcp"
        - "445/tcp"
        - "8090/tcp"

    - name: Create service dir
      ansible.builtin.file:
        path: "{{ media_dir }}/service"
        state: directory
        mode: '2775'
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: Copy config files to the service dir
      ansible.builtin.copy:
        src: ../Containers/
        dest: "{{ media_dir }}/service/"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0644"

    - name: Crate systemd unit file
      ansible.builtin.template:
        src: templates/podman-compose-systemd.j2
        dest: /etc/systemd/system/podman-compose@media1.service

    - name: Enable and start the podman-compose service
      ansible.builtin.systemd:
        name: podman-compose@media1.service
        state: started
        enabled: true
        daemon_reload: true
