gateway_api_enabled: true


# Metrics Server deployment
metrics_server_enabled: true



# Cert manager deployment
cert_manager_enabled: true
# Override the kubespray default versioncert_manager_namespace: "cert-manager"
cert_manager_version: "1.19.4"

# MetalLB deployment
metallb_enabled: false
metallb_speaker_enabled: "{{ metallb_enabled }}"
metallb_namespace: "metallb-system"
