cluster_name: malinka-cl.lan
kube_version: 1.34.7

# Make a copy of kubeconfig on the host that runs Ansible in {{ inventory_dir }}/artifacts
kubeconfig_localhost: true

# Enable strict ARP for kube-proxy to ensure proper routing of traffic to MetalLB-assigned IPs
kube_proxy_strict_arp: true


kubeadm_patches:
  - target: kube-apiserver
    type: strategic
    patch:
      spec:
        containers:
          - name: kube-apiserver
            resources:
              requests:
                cpu: "250m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"
